name: cardiac-fat-seg
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy<2.3
  - pydicom
  - simpleitk
  - openpyxl
  - nibabel
  - matplotlib
  - pandas
  - seaborn
  - scipy
  - plotly
